import Footer from "@/components/section/Footer";
import Navbar from "@/components/section/Navbar";
import Wrapper from "@/components/ui/Wrapper";
import "./globals.css";

export const metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Wrapper>
          <Navbar />
          {children}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
