import Footer from "@/components/section/Footer";
import Navbar from "@/components/section/Navbar";
import Wrapper from "@/components/ui/Wrapper";
import { Sora } from "@next/font/google";
import "./globals.css";
import Providers from "./providers";
// import { ClerkProvider } from '@clerk/nextjs'

const sora = Sora({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sora",
});

export const metadata = {
  title: "Dine Market",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <body>
        <Wrapper>
        <Navbar/>
          <main className={sora.variable}>
            <Providers>
              {children}</Providers>
          </main>
          <Footer />
        </Wrapper>
      </body>
    </html>
    // </ClerkProvider>
  );
}
